# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [echo, Siri]
patreon: # Replace with a single Patreon username mouse3687
open_collective: # Replace with a single Open Collective username voodoo.io
ko_fi: # Replace with a single Ko-fi username Toby
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., no fear act
liberapay: # Replace with a single Liberapay username Issa 
issuehunt: # Replace with a single IssueHunt username sans.org
otechie: # Replace with a single Otechie username turbo
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://Kotex.com', 'https://noom.com','https://nfl.com']
